### ISSUE TITLE
Add the publish step

### ISSUE THREAD

**Issue by edsu** [sul-dlss-labs/rialto-airflow#92]
The harvest DAG has a publish step, but it isn't currently doing anything. I think we should probably copy (or symlink) the newly created pubs and contribs parquet files in the snapshots folder to a place where the Jupyter Notebook environment can always find them, perhaps:

* /data/latest/publications.parquet
* /data/latest/contributions.parquet

**Comment by lwrubel** [comment]
Requested getting `/data` mounted to the `sul-notebook` VM: https://github.com/sul-dlss/operations-tasks/issues/3835

**Comment by lwrubel** [comment]
Share is mounted now.
